package dao;

import entity.Menu;
import java.util.List;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int deleteByPrimaryKey(Integer dishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    Menu selectByPrimaryKey(Integer dishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    List<Menu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int updateByPrimaryKey(Menu record);
}