package dao;

import entity.Restaurant;
import java.util.List;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int deleteByPrimaryKey(Integer restaurId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    Restaurant selectByPrimaryKey(Integer restaurId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    List<Restaurant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    int updateByPrimaryKey(Restaurant record);
}