package entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Id
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Name
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Sex
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Pwd
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Phone
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Email
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Message
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Pic
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Id
     *
     * @return the value of user_info.Id
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Id
     *
     * @param id the value for user_info.Id
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Name
     *
     * @return the value of user_info.Name
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Name
     *
     * @param name the value for user_info.Name
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Sex
     *
     * @return the value of user_info.Sex
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Sex
     *
     * @param sex the value for user_info.Sex
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Pwd
     *
     * @return the value of user_info.Pwd
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Pwd
     *
     * @param pwd the value for user_info.Pwd
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Phone
     *
     * @return the value of user_info.Phone
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Phone
     *
     * @param phone the value for user_info.Phone
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Email
     *
     * @return the value of user_info.Email
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Email
     *
     * @param email the value for user_info.Email
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Message
     *
     * @return the value of user_info.Message
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Message
     *
     * @param message the value for user_info.Message
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Pic
     *
     * @return the value of user_info.Pic
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Pic
     *
     * @param pic the value for user_info.Pic
     *
     * @mbg.generated Mon Aug 13 15:25:01 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", pwd='" + pwd + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", message='" + message + '\'' +
                ", pic='" + pic + '\'' +
                '}';
    }
}