package entity;

import java.util.Date;

public class Deliver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.deliver_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private Integer deliverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.deliver_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String deliverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.deliver_phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String deliverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.home_addr
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String homeAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.employ_date
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private Date employDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliver.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private Integer restaurId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.deliver_id
     *
     * @return the value of deliver.deliver_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public Integer getDeliverId() {
        return deliverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.deliver_id
     *
     * @param deliverId the value for deliver.deliver_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setDeliverId(Integer deliverId) {
        this.deliverId = deliverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.deliver_name
     *
     * @return the value of deliver.deliver_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getDeliverName() {
        return deliverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.deliver_name
     *
     * @param deliverName the value for deliver.deliver_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setDeliverName(String deliverName) {
        this.deliverName = deliverName == null ? null : deliverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.deliver_phone
     *
     * @return the value of deliver.deliver_phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getDeliverPhone() {
        return deliverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.deliver_phone
     *
     * @param deliverPhone the value for deliver.deliver_phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setDeliverPhone(String deliverPhone) {
        this.deliverPhone = deliverPhone == null ? null : deliverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.home_addr
     *
     * @return the value of deliver.home_addr
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getHomeAddr() {
        return homeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.home_addr
     *
     * @param homeAddr the value for deliver.home_addr
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setHomeAddr(String homeAddr) {
        this.homeAddr = homeAddr == null ? null : homeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.employ_date
     *
     * @return the value of deliver.employ_date
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public Date getEmployDate() {
        return employDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.employ_date
     *
     * @param employDate the value for deliver.employ_date
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setEmployDate(Date employDate) {
        this.employDate = employDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliver.restaur_id
     *
     * @return the value of deliver.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public Integer getRestaurId() {
        return restaurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliver.restaur_id
     *
     * @param restaurId the value for deliver.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setRestaurId(Integer restaurId) {
        this.restaurId = restaurId;
    }
}