package entity;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private Integer restaurId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.restaur_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String restaurName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.restaur_address
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String restaurAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.range
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String range;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.describe
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.fee
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    private Integer fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.restaur_id
     *
     * @return the value of restaurant.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public Integer getRestaurId() {
        return restaurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.restaur_id
     *
     * @param restaurId the value for restaurant.restaur_id
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setRestaurId(Integer restaurId) {
        this.restaurId = restaurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.restaur_name
     *
     * @return the value of restaurant.restaur_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getRestaurName() {
        return restaurName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.restaur_name
     *
     * @param restaurName the value for restaurant.restaur_name
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setRestaurName(String restaurName) {
        this.restaurName = restaurName == null ? null : restaurName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.restaur_address
     *
     * @return the value of restaurant.restaur_address
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getRestaurAddress() {
        return restaurAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.restaur_address
     *
     * @param restaurAddress the value for restaurant.restaur_address
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setRestaurAddress(String restaurAddress) {
        this.restaurAddress = restaurAddress == null ? null : restaurAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.phone
     *
     * @return the value of restaurant.phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.phone
     *
     * @param phone the value for restaurant.phone
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.range
     *
     * @return the value of restaurant.range
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.range
     *
     * @param range the value for restaurant.range
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setRange(String range) {
        this.range = range == null ? null : range.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.describe
     *
     * @return the value of restaurant.describe
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.describe
     *
     * @param describe the value for restaurant.describe
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.fee
     *
     * @return the value of restaurant.fee
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.fee
     *
     * @param fee the value for restaurant.fee
     *
     * @mbg.generated Sat Aug 18 21:16:41 CST 2018
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }
}